fix: update github actions, use arm architecture for macos, skip lint warnings

diff --git a/.github/workflows/ci-obj-c.yml b/.github/workflows/ci-obj-c.yml
--- a/.github/workflows/ci-obj-c.yml
+++ b/.github/workflows/ci-obj-c.yml
@@ -15,11 +15,11 @@ concurrency:
 jobs:
   build_test:
     name: Build & Test Objective-C Wrapper
-    if: false
-    runs-on: macos-11
+    if: "! contains(github.event.head_commit.message, '[skip ci]')"
+    runs-on: macos-12
     steps:
       - name: Checkout
-        uses: actions/checkout@v1
+        uses: actions/checkout@v3
 
       - name: Install Dependencies
         run: yarn install --frozen-lockfile
@@ -30,7 +30,17 @@ jobs:
       - name: Update binary for wrapper
         run: yarn wrapper:obj-c:update-binary
 
+      - name: List Installed Xcode Versions
+        run: |
+          echo "Listing installed Xcode versions:"
+          ls -1 /Applications | grep Xcode
+
+      - name: Verify Xcode Path
+        run: |
+          echo "Checking Xcode Developer Directory..."
+          ls -ld /Applications/Xcode_14.2.app/Contents/Developer || echo "Path not found or inaccessible"
+
       - name: Build and test wrapper
         run: yarn wrapper:obj-c:build
         env:
-          DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
+          DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
